# Generated by Django 4.1.13 on 2024-04-18 11:12

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InputOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('embedding_id', models.IntegerField()),
                ('inputoutput', models.ManyToManyField(to='myapp.inputoutput')),
                ('pinned_indices', models.ManyToManyField(blank=True, to='myapp.index')),
            ],
        ),
    ]
