# Generated by Django 4.1.13 on 2024-04-05 13:51

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=0, upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
