# Generated by Django 4.1.13 on 2024-04-11 10:19

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_document_file_id_remove_document_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=djongo.storage.GridFSStorage(collection='myfiles'), upload_to='pdf/'),
        ),
    ]
