# Generated by Django 4.1.13 on 2024-04-18 12:27

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_index_inputoutput_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='inputoutput',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='inputoutput',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='myapp.inputoutput'),
            preserve_default=False,
        ),
    ]
