# Generated by Django 4.1.13 on 2024-04-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_chathistory_inputoutput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='embedding_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
