# Generated by Django 4.1.13 on 2024-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_chathistory_embedding_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutput',
            name='response',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
