# Generated by Django 4.1.13 on 2024-04-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pdfdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='pdf_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='title',
            new_name='filename',
        ),
    ]
