# Generated by Django 4.1.13 on 2024-05-02 13:47

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_inputoutput_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='timeline',
            field=djongo.models.fields.JSONField(default=None, verbose_name='Timeline'),
        ),
        migrations.AddField(
            model_name='inputoutput',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='inputoutput',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='myapp.inputoutput'),
        ),
    ]
