# Generated by Django 4.1.13 on 2024-05-02 14:23

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_document_timeline_inputoutput_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='timeline',
            field=djongo.models.fields.JSONField(),
        ),
    ]
