# Generated by Django 4.1.13 on 2024-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_pdf_file_pdfdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
